sudo: required
language: generic

services:
  - docker
before_install:
  - docker build -t haneenakram/react-test-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true haneenakram/react-test-ci npm run test
  # e => environment variable make CI=true
  # CI=true => continuous integration mode, it will run the test once and exit
  # dont stuck in test suite waiting for more input